### ISSUE TITLE
Example fail with error

### ISSUE THREAD

**Issue by ssimm008** [kakearney/contourfcmap-pkg#2] opened 2015-02-27 21:11 UTC
With my R2014b, running your example
The option : 'method', 'calccontour',  gives the following error

Undefined function or variable "nnan".

Error in contourfcmap (line 495)
        [xn, yn] = polyjoin(xc(end-nnan-1:end), yc(end-nnan-1:end));

**Comment by kakearney** [comment] 2015-02-28 21:57
Thanks for letting me know; guess I didn't test things quite thoroughly
enough when I added support for data with NaNs a few weeks ago.  A fixed
version should be uploaded by tomorrow.

-Kelly

**Comment by ssimm008** [comment] 2015-03-01 01:33
Another quick thing on your example

v = version;

**Comment by kakearney** [comment] 2015-03-01 02:48
Yup, left that one out of the example.  Fixed now.  Thanks!

**Comment by ssimm008** [comment] 2015-03-01 14:28
Thanks for the quick fix

I guess I'm doing something wrong
Does this behavior look correct

[X,Y] = meshgrid(-8:.5:8);
R = sqrt(X.^2 + Y.^2) + eps;

Z = 40*sin(R)./R;
figure
imagesc(Z,[0 20])
colormap(jet)

clev = 0:20;
figure
cm = jet(length(clev)-1);
hc = contourfcmap(X,Y,R,clev,cm, ...
     'lo',[0 0 0],...
     'hi',[.9 .9 .9],...
      'method','calccontour',...
     'cbarloc','eastoutside');

**Comment by kakearney** [comment] 2015-03-01 15:00
It looks correct to me.  Did you mean to plot different data in the two
figures?  The first is showing Z, while the second plots R.  Note that if
you meant to plot R in the contour plot, you might need to increase the
resolution of X and Y to get the intended circular contours along the outer
portions.

**Comment by ssimm008** [comment] 2015-03-01 15:15
Sorry poor example; I was trying some of my own debugging.
How about this example?

(My first attempt at dropbox...hope it works)
https://www.dropbox.com/s/dt4vqwclxz8cfw2/Figure2a_NumericalExampleConstant.fig?dl=0

fileName = 'Figure2a_NumericalExampleConstant.fig';
uiopen(fileName,1)
colorbar off

ih = findobj('type','image');
x = get(ih,'XData');
y = get(ih,'YData');
[x,y] = meshgrid(x,y);
z = get(ih,'CData');
clev = [0 1:0.5:5 6:11];
figure
cm = jet(length(clev)-1);
cm(1,:) = [0.2 0.2 0.2];
hc = contourfcmap(x,y,z,clev,cm, ...
     'lo',[0 0 0],...
     'hi',[.9 .9 .9],...
      'method','calccontour',...
     'cbarloc','eastoutside');

Oddly enough, if I set nnan = 9; (ln 438), the result looks correct.

Sorry for all the trouble, I really like your tool. It provides more
insight to the data.

Thanks
Shaun

**Comment by kakearney** [comment] 2015-03-01 23:59
Well, I can confirm that there's something wonky going on in that example.  The recolor method is going a bit crazy with this one too, so I obviously broke something when I added in NaN support.  I'll have to look into it a bit more closely, but I don't think I'll have the time for that for another week or so.  For now, marking as a somewhat vague bug.

**Comment by ssimm008** [comment] 2015-03-02 15:39
I'm not sure why, but...

Comment lines 496-499 seems to work...I think
%         [xn, yn] = polyjoin(xc(end-nnan-1:end), yc(end-nnan-1:end));
%         for ii = 1:(length(S)-nnan)
%             [xc{ii}, yc{ii}] = polybool('-', xc{ii}, yc{ii}, xn, yn);
%         end

**Comment by kakearney** [comment] 2015-03-02 16:20
In theory, those lines are supposed to take the original set of contour
polygons (which extend through NaN-regions, if they exist) and clip away
the NaN portion.  If there are no NaNs in the data, I thought the xn/yn
data should be empty, and therefore it should have no effect (I'm on the
road without Matlab at the moment, so I can't look to see what's actually
going on).  Commenting it out should be a fine fix for plotting data
without any NaNs in it; I'll have to run it past some other test datasets
to get a robust solution for all input.

**Comment by kakearney** [comment] 2015-03-10 20:35
I believe I've now fixed this issue.

**Closed as completed by kakearney** 2015-03-10 20:35 UTC
Labels: bug
